import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MenuSidebar from "@/components/sidebar-menu/MenuSidebar";
import Seetings from "@/components/Seetings";
import Sidebar from "@/components/sidebar-menu/Sidebar";
import { IoMdMenu } from "react-icons/io";
import Navbar from "@/components/Navbar";
import { getDuas } from "@/lib/fetch-data";
import { log } from "console";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <div className="flex justify-between bg-bgGrayColor px-0 2xl:px-3 pt-0 2xl:pt-5 h-screen overflow-hidden">
          <div id="root" className="w-full px-5">
            <main className="flex gap-3">
              <div className="hidden xl:block mt-6">
                <MenuSidebar />
              </div>

              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
